export interface ProductDTOs {
    id: number,
    img: any,
    itemId: string,
    productName: string,
    description: string,
    pluName: string,
    price: string,
    createby: string,
    pattern: string,
    quantity: number,
    isAdded: any,
    pluCode: string;
    category: string;
    subCategory: string;
    measurement: string;
    size: string;
    weight: number;
    hsnCode?: any;
    createdBy: string;
    createdOn: string;
    lastUpdatedBy: string;
    lastUpdatedOn: string;
    purchaseprice: string;
    wastage: string;
    profitMargin: string;
    sellingPrice: string;
    marketPrice: string;
    title: string;
    imagePath: string;
    profitPrice: string;
    actualCost: string;
    seasonSale: string;
    itemGroup?: any;
    mgfCode?: any;
    gstPer?: any;
    sgstPer?: any;
    cgstPer?: any;
    manufracture: string;
    offerType?: any;
    foodSegment: string;
    totalViews: number;
    totalFavs: number;
    sellingVarience: string;
    itemSellingType: string;
    supplier: string;
    featured: string;
    promoVideoLink: string;
    longDescription: string;
    mainCategory: string;
    featuredStartDate: string;
    approval: string;
    offerId: string;
    stockType: string;
    netWeight: number;
    totalStock: string;
    maxQuantityAllowed: number;
    brand: string;
    tag: string;
    itemType: string;
    visibility: number;
    coupenDisc?: any;
    relation: number;
    relationValue?: any;
    parentItemId?: any;
    taxValue?: any;
    isTaxFree?: any;
    kotPrint?: any;
    kotPrintDesc?: any;
    checkSpecail?: any;
    foodType?: any;
    foodSubType?: any;
    spicyLevel?: any;
    availableDay: number;
    mealTimeType: string;
    startTime: string;
    preparationTime: string;
    isSpecialDay: string;
    endTime: string;
    item_MeasuredIn?: any;
    vatPer?: any;
    hub: string;
    isWishlisted?: any;
    wishlistId?: any;
    priceId?: any;
    imagesCount?:any;
    iFrame:any
  }
